### ISSUE TITLE
Content & marketing checklist 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#28]
Why: Asim suggested to focus on content that adds value, is engaging and is easy to market
What: create checklist, monitor content, adjust content as needed, maximize marketing efforts
Owner: Anita

Content checklist:
- [ ] Engaging website with interactive graphics
- [ ] Interesting findings people can quote/share on social media
- [ ] Making sharing parts of this report easy
- [ ] Have a whole page for quotes on the website 
- [ ] Quotes from industry leaders, their companies are more likely to promote the report and perhaps even get us some press coverage. 

Marketing checklist:
- [ ] Asking each of our member orgs to give us a quote in exchange for some actual publicity 
- [ ] Reaching out to journalists we do know and pitching to them
- [ ] Creating short animations to explain certain findings of the report, teasing people as we go along.
