### ISSUE TITLE
PR FAQ checklist

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#29]
Why: Asim suggested to focus on content that adds value and skip content that is less relevant (esp. if we run out of time)
What: create checklist based on pr faq, prioritize content, adjust content as needed
Next steps: we can try to create a [spreadsheet](https://docs.google.com/spreadsheets/d/1xFez2f5F9ope7x6MPxclW9uRk3SUaHelHmQv9U2sLEE/edit#gid=0) for this but for now I'm logging here all the criteria in one place
Owner: Anita

Criteria to be considered when prioritizing content:
- Does it reduce confusion?
- Does it help drive investment into green software?
- Does it help people trust the report and it's findings?
E.g. important work that helps document the current state of green software but which doesn't help achieve the above, would be first to be cut from the report.

Required content based on the [PR FAQ](https://github.com/Green-Software-Foundation/pr-faqs/blob/9370ee84b27df0e57ec0ae8d4be18730c8cd67af/live/state-of-green-software.pr-faq.md):
- [ ] What is the **current state** related to green software? 
- [ ] What are the  **future trends** related to green software?
- [ ] What is the state of the art re: green software research, incl. the correct most up-to-date stats we should all be quoting?
- [ ] What is the user experience regarding green software from the perspective of software practitioners?
- [ ] What is the user experience regarding green software from the perspective of executive leadership?
- [ ] Who are the key actors (industry bodies, advocacy groups, regulatory bodies, environmental coalitions)?
- [ ] What high-impact policy events are on the horizon that impact green software?
- [ ] What high-impact upcoming regulation is on the horizon that impacts green software?
- [ ] What green software open-source tooling is currently available, and where are the gaps?
- [ ] The report will highlight gaps in the green software ecosystem and drive investment toward filling those gaps. 
- [ ] It will help people understand what kind of motivations will result in the best outcomes. 
- [ ] It will better prepare organizations for upcoming regulations and policies. 
- [ ] It will reduce duplication of effort by shining a light on the activity’s key actors are already engaged in
