### ISSUE TITLE
SOGS – Weekly Sprint #1

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#71]
Continuation of [Tasks for Ismael for December](https://github.com/Green-Software-Foundation/state-of-green-software/issues/69) 

Next steps for @Leamsi9 (ETAs confirmed by him this evening):
- [ ] If needed, @jawache & @Leamsi9 to keep working on the [business case](https://docs.google.com/document/d/1cgy-38nOnW3L98d7mr4OnInHVxKpR2zd/edit) re: https://github.com/Green-Software-Foundation/state-of-green-software/issues/48
- [ ] ETA hopefully today Dec 2 https://github.com/Green-Software-Foundation/state-of-green-software/issues/50
- [ ] ETA Dec 9 https://github.com/Green-Software-Foundation/state-of-green-software/issues/51
- [ ] ETA Dec 16 https://github.com/Green-Software-Foundation/state-of-green-software/issues/49
- [ ] ETA Dec 16 (rewrite) https://github.com/Green-Software-Foundation/state-of-green-software/issues/48

Other prioirity todos:
- [ ] https://github.com/Green-Software-Foundation/state-of-green-software/issues/23
- [ ] https://github.com/Green-Software-Foundation/state-of-green-software/issues/26
- [ ] https://github.com/Green-Software-Foundation/state-of-green-software/issues/67

**Comment by holanita** [comment]
@Leamsi9 from now on I'll create these weekly agendas just like for all other projects. please focus on the top section that summarizes your next steps. cc @jawache

**Comment by holanita** [comment]
Summary on what was discussed today, to be turned into GH issues as needed later:

Important next steps:
- Asim to reach out to the SC next week to see if there are other members who could push the survey like Avanade just did
- I'll see how much it would cost to buy responses through Survey Monkey and how fast they could deliver 
- Tamara will do some interviews with academics who are easy to approach within a reasonable timeframe

This might not be doable:
- For respondents who are open to follow-up questions, we might create a short survey of 4 open ended Qs ([example](https://docs.google.com/document/d/1wNp2vBkwuvMnvcdyXR3VH9Pt8XaixrvPTaUGgfnGgew/edit?disco=AAAAhSS0HOE)).
- BUT we might have to remove the question where we ask for email addresses. TBD.
- If we do this, Ismael should screen through the answers (characters will be limited).

**Comment by holanita** [comment]
Ismael's part to be continued here: https://github.com/Green-Software-Foundation/state-of-green-software/issues/82
Tamara's part to be continued here: https://github.com/Green-Software-Foundation/state-of-green-software/issues/27
