### ISSUE TITLE
SOGS – Weekly Sprint #2

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#82]
Continuation of [Tasks for Ismael for December](https://github.com/Green-Software-Foundation/state-of-green-software/issues/69) 

_We haven't heard from Ismael for a long time. I'll continue adding weekly sprints as Asim had suggested, although it might not add value if there is no progress to track or discuss. Let me know if you guys want to change the process._

- [ ] If needed, @jawache & @Leamsi9 to keep working on the [business case](https://docs.google.com/document/d/1cgy-38nOnW3L98d7mr4OnInHVxKpR2zd/edit) re: https://github.com/Green-Software-Foundation/state-of-green-software/issues/48
- [x] Late, no news – ETA Dec 2 https://github.com/Green-Software-Foundation/state-of-green-software/issues/50
- [ ] Late, no news – ETA Dec 9 https://github.com/Green-Software-Foundation/state-of-green-software/issues/51
- [ ] Due this week, no news – ETA Dec 16 https://github.com/Green-Software-Foundation/state-of-green-software/issues/49
- [ ] Due this week, no news – ETA Dec 16 https://github.com/Green-Software-Foundation/state-of-green-software/issues/48 (rewrite) 
- [ ] No news – https://github.com/Green-Software-Foundation/state-of-green-software/issues/68
- [ ] No news – https://github.com/Green-Software-Foundation/state-of-green-software/issues/33

**Comment by holanita** [comment]
As agreed on the call, we should be able to mark the desk research as done by the end of next week (including review).

**Comment by holanita** [comment]
@Leamsi9 @jawache just a reminder on what we had agreed on before the holidays.
