### ISSUE TITLE
Epic - Oleg Handover

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/state-of-green-software#94]
**Process the desktop research**
- [ ] Tamara review & validate existing insights.
- [ ] Technical writer review the wording
- [ ] Namrata approve the insight title text or suggest another text
- [ ] Have graphic assets created for each insight.
- [ ] Have cover/share graphic created for each insight.

**Process Survey Data**
- [ ] Create X new insights from survey responses
- [ ] Technical writer review the wording
- [ ] Namrata approve the insight title text or suggest another text
- [ ] Have graphic assets created for each insight.
- [ ] Have cover/share graphic created for each insight.

**Process Interview** (low priority, we didn't do many interviews)
- [ ] Create X new insights from survey responses
- [ ] Technical writer review the wording
- [ ] Namrata approve the insight title text or suggest another text
- [ ] Have graphic assets created for each insight.
- [ ] Have cover/share graphic created for each insight.

**Website**
- [ ] Convert google doc to markdown and format it into whatever developer needs for the website.
- [ ] Live "in-progress" website link we can review with insights as we add them, with a selection of different types.

**Pre-release checklist**
- [ ] Consistency review process (Everyone 2 weeks to give their final comments, then the SC gives a final vote).
- [ ] Launch + marketing plan with Namrata.

**Comment by jawache** [comment]
## Workflow (5 steps)

- Tamara drafts (gdoc)
- Editor reviews (gdoc)
- Marketing reviews content (gdoc)
- Graphics created (gdoc -> assets)
- Published (gdoc -> md)

## Milestones & KPI
Cohort 1 - 6 insights. average %age complete. 80%
Cohort 2 - X insights. %age complete.
Cohort 3 - X insights. %age complete.
Cohort 4 - X insights. %age complete.
Cohort 5 - X insights. %age complete.
